[build]
  command = "npm run build"
  publish = ".next-build"

[[edge_functions]]
function = "googlebotBypass"
path = "/resources"

[[edge_functions]]
function = "googlebotBypass"
path = "/resources/*"

[[edge_functions]]
function = "googlebotBypass"
path = "/solutions"

[[edge_functions]]
function = "googlebotBypass"
path = "/solutions/*"
